
export PDSH_RCMD_TYPE=ssh
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

export EXPERIMENT_DIR=/opt/ventura/framework
export EXPERIMENT_JOBS_DIR=$EXPERIMENT_DIR/flink-build-jobs

alias ll='ls -lah'
alias l='ls -lah'


